### PR TITLE
[WIP] Draft for new function interface

### PR DESCRIPTION
**Pull request by andresmgot**
This is a draft for the new function interface. It is highly based in the suggestions of [OpenEvents](https://docs.google.com/document/d/1PaoxJZEbEfo_OTdML5phAFlXhljq3HYtcZAN6FqPt3E/edit#heading=h.j978froxpjkz) but with the number of parameters that Lambda uses (one for the `event` data and other for the function general `context`). This is also compatible with some OpenWhisk and Lambda functions since the first arguments has the same properties than the `params` object that they use (pair `key/value` for the first parameter of the function). Note that the value returned by the user function is the one that will be used as HTTP response.

The function runtime relies in http headers in order to obtain information about the event source.

This is the function format as YAML:
```yml
event:                                  # Event data
  foo: bar                              # Parameter when calling the function with a JSON object
context:
  event-id: 123123
  event-type: application/json
  event-time: timestamp
  event-namespace: 'kafka.kubeless.io'
  extensions:                           # Optional parameters, used to expose HTTP request properties and function context
    function-name: pubsub-nodejs
    timeout: 180
    runtime: nodejs6
    memory-limit: 128M
```

This would be a sample function (javascript):
```js
module.exports = {
  foo: function (event, context) {
    return 'hello ' + event.name;
  }
}
```
```console
$ kubeless function call get-nodejs --data '{"name": "andres"}'
"hello andres"
```

### CODE REVIEW

**Comment by sebgoa** [comment]
openevents is now cloudevent and the spec is in github:

https://github.com/cloudevents/spec

**Comment by sebgoa** [comment]
fwiw, lambda function context attributes and methods:
https://docs.aws.amazon.com/lambda/latest/dg/python-context-object.html#python-context-object-methods

Lambda events:
https://docs.aws.amazon.com/lambda/latest/dg/eventsources.html

**Comment by sebgoa** [comment]
I guess you want `event-emitter` to be the namespace from cloudevents ?

Your indentation seems a bit messed up foo, data, event-type and resource should be at the same level ?

**Comment by andresmgot** [comment]
@sebgoa:
> I guess you want event-emitter to be the namespace from cloudevents ?

yes, that was the intention. I thought that calling it `namespace` would be a bit confusing for our case.

> Your indentation seems a bit messed up foo, data, event-type and resource should be at the same level ?

Just realized that. I fixed it: yes, foo, data and event-type are at the same level.

**Comment by andresmgot** [comment]
I've added the requested headers in the kubeless CLI and I've adapted the Python runtime to the new format.

**Comment by murali-reddy** [comment]
There are actually two changes in this draft.

- standardizing function handler signature to

``` python
def foobar(event, context):
```
- event listener is decoupled from laguage runtime + function container image. So event listener actually gets the data and calls the service exposed in runtime + function container image, as per the format. Question is how and where the event listener runs.

First part is clear and looks good. IMO, on second part, we need to consider if this is really required change. If desirable then how does custom triggers and customer runtime fit in to this model. What are the performance implications.

**Comment by andresmgot** [comment]
> event listener is decoupled  -> we need to consider if this is really required change

IMO it is a required change, in order to support a new runtime it should not be needed to write all the possible event listeners in the new runtime language.

> If desirable then how does custom triggers and customer runtime fit in to this model. What are the performance implications.

I am not sure I fully understand your question, this diff does not specify how to implement new triggers (or event listeners): it just removes them from the same container than the one that executes the user function. Regarding performance: it should not be highly affected if the event listener is run as a sidecar container, if it is in a different pod there is an extra jump so we may want to avoid that approach.

**Comment by murali-reddy** [comment]
I did not clearly communicate on this part:

>IMO, on second part, we need to consider if this is really required change. If desirable then how does custom triggers and customer runtime fit in to this model. What are the performance implications.

>IMO it is a required change, in order to support a new runtime it should not be needed to write all the possible event listeners in the new runtime language.

this could be necessary change, but warrants discussion on its own. First item sort of provides developer documentation on how to write a handler i.e) required handler signature, and request/response format. This does not change irrespective of trigger/runtime separation.

**Comment by deissnerk** [comment]
@andresmgot @murali-reddy Sorry, but I'm a bit lost. What exactly do you mean by event handler? My understanding was that this is a new unified interface to call functions. So I would expect a trigger implementation to do the HTTP calls accordingly.

**Comment by andresmgot** [comment]
Yes, the interface will be unique and common regardless of the event source. The only problem is that we need a piece of software (some kind of gateway) that translates for example a Kafka message to a request that have all the information.

**Comment by joek** [comment]
Here are the details how openwhisk is dealing with http responses. In general they expect a response struct which allows to set headers etc. 

https://github.com/apache/incubator-openwhisk/blob/master/docs/webactions.md

At least in our use case we will use http triggers a lot and need definitely more control over the http response. Maybe we can help you with that topic. We have grooming tomorrow, I will talk with the team about it.

**Comment by joek** [comment]
Another thing to add here:
- Do we still need this `module.exports` in nodejs? I would prefer if we just have to put a function definition using a predefined function name.

```
function main(event, context) {
    return 'hello ' + event.name;
}
```
If we have a predefined function name, we can make the --handler parameter optional.

**Comment by andresmgot** [comment]
hi @joek,

regarding having a feature similar to openwhisk `webactions` I do agree that it is something interesting. Maybe you can open an issue to implement that feature? Uses cases for that will be great.

Regarding your suggestion about having a predefined function name I am not convinced because:
 - It would be more tricky to execute. Since the function won't be exposed we would need to workaround something to execute it.
 - It requires to know that we are using that convention (that may not be obvious for some new user). Also it would require to discard the field `handler` for all the functions (so we will need to do the same for all the languages).
 - It would not be possible to reuse the same file in several functions (see [this example](https://github.com/kubeless/functions/blob/master/incubator/rest-api/server.js))

Also, just to clarify, this PR has not been updated with the latest changes. I am going to close it just to avoid confusions but I am happy to follow conversations in this PR, in [the one I opened in the kubeless repo](https://github.com/kubeless/kubeless/pull/596) or in slack.

**Pull request closed without merging**
